name: CI
on: [push, pull_request]

run-name: "CI run for ${{ github.head_ref || github.ref }}"

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."

      - name: Deploy
        run: |
          echo "Deploying..."
