name: Print GitHub Ref

on:
  pull_request:
    types: [closed]

jobs:
 print-ref:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Print GitHub Ref
       run: echo "${{ toJSON(github) }}"
